[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vessegen"
version = "1.0.0"
dependencies = []
requires-python = ">=3.8"

[project.scripts]
vessegen = "vessegen.__main__:main"

[tool.setuptools]
packages = ["vessegen"]
